pipeline {
    agent any
    
    properties([
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '30', numToKeepStr: '3')),
        disableConcurrentBuilds(), 
        disableResume(),
        parameters([choice(choices: ['apply', 'destroy'],name: 'TERAFORM_ACTION')])]
    )

    stages {

        stage('chectout') {
            steps {
                echo '#----------------Checkout SCM------------------#'
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/mohamedanwer006/iti-terrafrom-project.git'

                sh 'ls'
            }
        }

        stage('initialize') {
            steps {
                echo '#----------------Terraform Initialization------------------#'
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws_credentials',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]){

                        sh 'terraform init'
                    }
            }
        }
        
         stage('validate') {
            steps {
                echo '#----------------Terraform Validate------------------#'
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws_credentials',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]){

                        sh 'terraform validate'
                    }
            }
        }

        stage('build') {
            steps {
               
                echo '#----------------Terraform ${TERAFORM_ACTION}------------------#'
                
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws_credentials',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]){

                        sh 'terraform ${TERAFORM_ACTION} -var-file prod.tfvars --auto-approve'
                        
                    }
            }
        }
    }
}
